"""agents/cli_completion.py — tab-completion script generator (G11, 2026-05-03).

Emits a bash / zsh completion fragment for the `aim` CLI. Designed to
be sourced from `~/.bashrc` / `~/.zshrc`:

    eval "$(python -m agents.cli_completion bash)"
    eval "$(python -m agents.cli_completion zsh)"

The generated script enumerates:
  * top-level commands (read from aim_cli._HANDLERS keys at gen time)
  * dynamic completions for project / routine names (resolved at
    completion time by spawning a sub-process with `--list-...`)

Public API:
    bash_script() -> str
    zsh_script()  -> str
    list_projects() -> list[str]
    list_routines() -> list[str]
"""
from __future__ import annotations

import logging
from typing import Optional

log = logging.getLogger("aim.cli_completion")


# ── source-of-truth lookups ──────────────────────────────────────


def list_subcommands() -> list[str]:
    try:
        from aim_cli import _HANDLERS
    except ImportError:
        return []
    return sorted(_HANDLERS.keys())


def list_projects() -> list[str]:
    try:
        from agents import project_owner as po
        return po.list_projects()
    except Exception:
        return []


def list_routines() -> list[str]:
    try:
        from agents.routines import list_routines as _lr
        return _lr()
    except Exception:
        return []


# ── shell scripts ───────────────────────────────────────────────


_PROJECT_SUBS = ["list", "archive", "unarchive", "sweep", "transition"]
_PHASES = ["DRAFT", "REVIEW", "SUBMITTED", "ACCEPTED",
           "PUBLISHED", "REJECTED", "ARCHIVED"]


def bash_script() -> str:
    cmds = " ".join(list_subcommands())
    project_subs = " ".join(_PROJECT_SUBS)
    phases = " ".join(_PHASES)
    return f"""\
# aim CLI completion (bash) — generated by agents.cli_completion
_aim_complete() {{
    local cur prev words cword
    _init_completion || return

    local CMDS="{cmds}"
    local PROJECT_SUBS="{project_subs}"
    local PHASES="{phases}"

    if [[ $cword -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$CMDS" -- "$cur") )
        return
    fi

    case "${{words[1]}}" in
        project)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "$PROJECT_SUBS" -- "$cur") )
            elif [[ $cword -eq 3 ]]; then
                local PROJECTS=$(python3 -c \
                  'from agents.cli_completion import list_projects; print(" ".join(list_projects()))' 2>/dev/null)
                COMPREPLY=( $(compgen -W "$PROJECTS" -- "$cur") )
            elif [[ $cword -eq 4 && "${{words[2]}}" == "transition" ]]; then
                COMPREPLY=( $(compgen -W "$PHASES" -- "$cur") )
            fi
            ;;
        routine)
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "list run" -- "$cur") )
            elif [[ $cword -eq 3 && "${{words[2]}}" == "run" ]]; then
                local ROUTINES=$(python3 -c \
                  'from agents.cli_completion import list_routines; print(" ".join(list_routines()))' 2>/dev/null)
                COMPREPLY=( $(compgen -W "$ROUTINES" -- "$cur") )
            fi
            ;;
        brief)
            if [[ "$prev" == "--project" ]]; then
                local PROJECTS=$(python3 -c \
                  'from agents.cli_completion import list_projects; print(" ".join(list_projects()))' 2>/dev/null)
                COMPREPLY=( $(compgen -W "$PROJECTS" -- "$cur") )
            else
                COMPREPLY=( $(compgen -W "--project --lang" -- "$cur") )
            fi
            ;;
    esac
}}
complete -F _aim_complete aim
"""


def zsh_script() -> str:
    """Minimal zsh wrapper that sources the bash script via bashcompinit."""
    return (
        "# aim CLI completion (zsh) — generated by agents.cli_completion\n"
        "autoload -Uz bashcompinit && bashcompinit\n"
        + bash_script()
    )


def _main() -> int:
    import argparse, sys
    ap = argparse.ArgumentParser(description="aim CLI completion generator")
    ap.add_argument("shell", choices=("bash", "zsh"),
                    help="target shell")
    args = ap.parse_args()
    print(bash_script() if args.shell == "bash" else zsh_script())
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
