//! aim-cli-completion — bash / zsh completion script generator.
//!
//! Port of `agents/cli_completion.py`. Emits a shell fragment that can
//! be sourced from `~/.bashrc` / `~/.zshrc`. Source-of-truth lookups
//! (subcommand list, projects, routines) are pluggable via the
//! [`Sources`] trait so tests don't need a live `aim` binary.

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CompletionError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

pub type Result<T> = std::result::Result<T, CompletionError>;

// ── canonical static sub-tokens (verbatim from Python) ──────────────────────

pub const PROJECT_SUBS: &[&str] = &[
    "list",
    "archive",
    "unarchive",
    "sweep",
    "transition",
];

pub const PHASES: &[&str] = &[
    "DRAFT",
    "REVIEW",
    "SUBMITTED",
    "ACCEPTED",
    "PUBLISHED",
    "REJECTED",
    "ARCHIVED",
];

// ── pluggable sources ──────────────────────────────────────────────────────

pub trait Sources: Send + Sync {
    fn list_subcommands(&self) -> Vec<String>;
    fn list_projects(&self) -> Vec<String>;
    fn list_routines(&self) -> Vec<String>;
}

/// Empty stub for binaries that haven't wired in real sources yet.
pub struct EmptySources;
impl Sources for EmptySources {
    fn list_subcommands(&self) -> Vec<String> {
        Vec::new()
    }
    fn list_projects(&self) -> Vec<String> {
        Vec::new()
    }
    fn list_routines(&self) -> Vec<String> {
        Vec::new()
    }
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StaticSources {
    pub subcommands: Vec<String>,
    pub projects: Vec<String>,
    pub routines: Vec<String>,
}

impl Sources for StaticSources {
    fn list_subcommands(&self) -> Vec<String> {
        self.subcommands.clone()
    }
    fn list_projects(&self) -> Vec<String> {
        self.projects.clone()
    }
    fn list_routines(&self) -> Vec<String> {
        self.routines.clone()
    }
}

// ── script generation ──────────────────────────────────────────────────────

/// Build the bash completion script. Mirrors Python `bash_script` 1:1
/// (top-level commands, project/routine subcommands, phases, dynamic
/// project/routine lookup via `aim --list-...` sub-shell calls).
pub fn bash_script(sources: &dyn Sources) -> String {
    let cmds = {
        let mut v = sources.list_subcommands();
        v.sort();
        v.join(" ")
    };
    let project_subs = PROJECT_SUBS.join(" ");
    let phases = PHASES.join(" ");
    format!(
        "# aim CLI completion (bash) — generated by aim-cli-completion\n\
_aim_complete() {{\n\
    local cur prev words cword\n\
    _init_completion || return\n\
\n\
    local CMDS=\"{cmds}\"\n\
    local PROJECT_SUBS=\"{project_subs}\"\n\
    local PHASES=\"{phases}\"\n\
\n\
    if [[ $cword -eq 1 ]]; then\n\
        COMPREPLY=( $(compgen -W \"$CMDS\" -- \"$cur\") )\n\
        return\n\
    fi\n\
\n\
    case \"${{words[1]}}\" in\n\
        project)\n\
            if [[ $cword -eq 2 ]]; then\n\
                COMPREPLY=( $(compgen -W \"$PROJECT_SUBS\" -- \"$cur\") )\n\
            elif [[ $cword -eq 3 ]]; then\n\
                local PROJECTS=$(aim --list-projects 2>/dev/null)\n\
                COMPREPLY=( $(compgen -W \"$PROJECTS\" -- \"$cur\") )\n\
            elif [[ $cword -eq 4 && \"${{words[2]}}\" == \"transition\" ]]; then\n\
                COMPREPLY=( $(compgen -W \"$PHASES\" -- \"$cur\") )\n\
            fi\n\
            ;;\n\
        routine)\n\
            if [[ $cword -eq 2 ]]; then\n\
                COMPREPLY=( $(compgen -W \"list run\" -- \"$cur\") )\n\
            elif [[ $cword -eq 3 && \"${{words[2]}}\" == \"run\" ]]; then\n\
                local ROUTINES=$(aim --list-routines 2>/dev/null)\n\
                COMPREPLY=( $(compgen -W \"$ROUTINES\" -- \"$cur\") )\n\
            fi\n\
            ;;\n\
        brief)\n\
            if [[ \"$prev\" == \"--project\" ]]; then\n\
                local PROJECTS=$(aim --list-projects 2>/dev/null)\n\
                COMPREPLY=( $(compgen -W \"$PROJECTS\" -- \"$cur\") )\n\
            else\n\
                COMPREPLY=( $(compgen -W \"--project --lang\" -- \"$cur\") )\n\
            fi\n\
            ;;\n\
    esac\n\
}}\n\
complete -F _aim_complete aim\n",
        cmds = cmds,
        project_subs = project_subs,
        phases = phases,
    )
}

/// Wraps [`bash_script`] in a zsh `bashcompinit` autoload preamble.
pub fn zsh_script(sources: &dyn Sources) -> String {
    format!(
        "# aim CLI completion (zsh) — generated by aim-cli-completion\n\
autoload -Uz bashcompinit && bashcompinit\n\
{}",
        bash_script(sources)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> StaticSources {
        StaticSources {
            subcommands: vec!["chat".into(), "brief".into(), "project".into(), "routine".into()],
            projects: vec!["AIM".into(), "CDATA".into(), "MCAOA".into()],
            routines: vec!["morning_brief".into(), "nightly_compact".into()],
        }
    }

    // ── constants ───────────────────────────────────────────────────────────

    #[test]
    fn project_subs_matches_python() {
        assert!(PROJECT_SUBS.contains(&"list"));
        assert!(PROJECT_SUBS.contains(&"transition"));
        assert_eq!(PROJECT_SUBS.len(), 5);
    }

    #[test]
    fn phases_matches_python() {
        assert_eq!(PHASES.len(), 7);
        assert!(PHASES.contains(&"DRAFT"));
        assert!(PHASES.contains(&"PUBLISHED"));
    }

    // ── EmptySources ───────────────────────────────────────────────────────

    #[test]
    fn empty_sources_returns_empty_lists() {
        let s = EmptySources;
        assert!(s.list_subcommands().is_empty());
        assert!(s.list_projects().is_empty());
        assert!(s.list_routines().is_empty());
    }

    // ── bash_script ────────────────────────────────────────────────────────

    #[test]
    fn bash_script_lists_subcommands_sorted_in_cmds() {
        let s = fixture();
        let script = bash_script(&s);
        assert!(script.contains("CMDS=\"brief chat project routine\""));
    }

    #[test]
    fn bash_script_includes_project_subs_constant() {
        let s = fixture();
        let script = bash_script(&s);
        assert!(script.contains("PROJECT_SUBS=\"list archive unarchive sweep transition\""));
    }

    #[test]
    fn bash_script_includes_phases_constant() {
        let s = fixture();
        let script = bash_script(&s);
        assert!(script.contains("PHASES=\"DRAFT REVIEW SUBMITTED ACCEPTED PUBLISHED REJECTED ARCHIVED\""));
    }

    #[test]
    fn bash_script_has_complete_directive() {
        let s = fixture();
        let script = bash_script(&s);
        assert!(script.trim_end().ends_with("complete -F _aim_complete aim"));
    }

    #[test]
    fn bash_script_routes_project_subcommand() {
        let s = fixture();
        let script = bash_script(&s);
        assert!(script.contains(r#"case "${words[1]}""#));
        assert!(script.contains("project)"));
        assert!(script.contains("routine)"));
        assert!(script.contains("brief)"));
    }

    #[test]
    fn bash_script_uses_aim_subshell_for_dynamic_lists() {
        let s = fixture();
        let script = bash_script(&s);
        // Dynamic projects (resolved at completion time, not gen time)
        assert!(script.contains("aim --list-projects 2>/dev/null"));
        assert!(script.contains("aim --list-routines 2>/dev/null"));
    }

    #[test]
    fn bash_script_handles_empty_subcommands() {
        let s = StaticSources::default();
        let script = bash_script(&s);
        assert!(script.contains(r#"CMDS="""#));
    }

    // ── zsh_script ─────────────────────────────────────────────────────────

    #[test]
    fn zsh_script_includes_bashcompinit_preamble() {
        let s = fixture();
        let script = zsh_script(&s);
        assert!(script.starts_with("# aim CLI completion (zsh)"));
        assert!(script.contains("autoload -Uz bashcompinit"));
        // and embeds the bash body
        assert!(script.contains("complete -F _aim_complete aim"));
    }

    #[test]
    fn zsh_script_contains_bash_body_unchanged() {
        let s = fixture();
        let zsh = zsh_script(&s);
        let bash = bash_script(&s);
        assert!(zsh.contains(&bash));
    }
}
