"""AI/ai/case_archiver.py — CA1 (2026-05-04).

When FE1 generates a regression eval case for a finding, that case
sits in AIM_EVAL_CASES_DIR forever. If subsequent diagnostics never
flag the same finding again — the bug is fixed and the case is just
noise. This module moves such "resolved" cases into an archive
subdirectory so the active eval suite stays focused.

Heuristic for "resolved":
  - Case was generated by FE1 (id starts with `regr-`).
  - Last K ledger reports do NOT contain the finding the case codified
    (we recover the finding ref from the case id by inverting the slug).
  - Case is at least `min_age_days` old (avoid archiving brand-new cases).

Public API:
    candidates(*, lookback=7, min_age_days=3) -> list[Candidate]
    archive(*, lookback=7, min_age_days=3, dry_run=False) -> ArchiveResult
"""
from __future__ import annotations

import dataclasses
import datetime as dt
import logging
import os
import re
import shutil
from pathlib import Path
from typing import Optional

log = logging.getLogger("ai.case_archiver")


@dataclasses.dataclass
class Candidate:
    case_id: str
    case_path: Path
    inferred_ref_path: str       # the file path piece, no line
    inferred_ref_line: Optional[int]
    age_days: float


@dataclasses.dataclass
class ArchiveResult:
    n_candidates: int
    n_moved: int
    moved: list[Path]
    archive_dir: Path


def _cases_dir() -> Path:
    env = os.environ.get("AIM_EVAL_CASES_DIR")
    if env:
        return Path(env)
    return Path.home() / ".cache" / "aim" / "eval_cases"


def _archive_dir() -> Path:
    env = os.environ.get("AIM_EVAL_ARCHIVE_DIR")
    if env:
        return Path(env)
    return _cases_dir() / "_archived"


_ID_RE = re.compile(r"^regr-(?P<slug>[\w-]+?)(?:-l(?P<line>\d+))?$")


def _ref_from_id(case_id: str) -> Optional[tuple[str, Optional[int]]]:
    """Invert FE1's `_slug` heuristic well enough to recover the
    file ref. We can't always reconstruct the EXACT path (the slug is
    lossy: `agents/x.py` → `agents-x-py`), so we collapse separators
    and compare against ledger findings using the same collapse."""
    m = _ID_RE.match(case_id)
    if not m:
        return None
    line = int(m.group("line")) if m.group("line") else None
    return (m.group("slug"), line)


def _normalise_ref(ref: str) -> tuple[str, Optional[int]]:
    """Match FE1's `_slug`: lowercase, non-alnum → `-`."""
    slug_re = re.compile(r"[^a-z0-9]+")
    if ":" in ref:
        path, _, lpart = ref.rpartition(":")
        if lpart.isdigit():
            slug = slug_re.sub("-", path.lower()).strip("-")
            return (slug, int(lpart))
    slug = slug_re.sub("-", ref.lower()).strip("-")
    return (slug, None)


def _findings_in_recent_reports(lookback: int) -> set[tuple[str, Optional[int]]]:
    from AI.ai.diagnostic_ledger import recent
    rows = recent(n=lookback)
    seen: set[tuple[str, Optional[int]]] = set()
    for r in rows:
        if not r.report_path:
            continue
        p = Path(r.report_path)
        if not p.exists():
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        from AI.ai.meta_evaluator import parse_report
        for ref in parse_report(text).findings:
            seen.add(_normalise_ref(ref))
    return seen


def _age_days(p: Path) -> float:
    try:
        mtime = p.stat().st_mtime
    except OSError:
        return 0.0
    delta = dt.datetime.now().timestamp() - mtime
    return delta / 86400.0


def candidates(*, lookback: int = 7,
               min_age_days: float = 3.0) -> list[Candidate]:
    """Return the regression cases that look ready to archive."""
    cases = _cases_dir()
    if not cases.exists():
        return []
    seen_refs = _findings_in_recent_reports(lookback)
    out: list[Candidate] = []
    for p in sorted(cases.glob("regr-*.yaml")):
        cid = p.stem
        ref = _ref_from_id(cid)
        if ref is None:
            continue
        age = _age_days(p)
        if age < min_age_days:
            continue
        # Match by (slug, line). If line absent in the case id, fall back
        # to slug-only match.
        if ref in seen_refs:
            continue
        if ref[1] is None:
            # slug-only case → archive only if no recent finding shares
            # the slug at any line
            slug_hits = any(s == ref[0] for s, _ in seen_refs)
            if slug_hits:
                continue
        out.append(Candidate(
            case_id=cid, case_path=p,
            inferred_ref_path=ref[0],
            inferred_ref_line=ref[1],
            age_days=age,
        ))
    return out


def archive(*, lookback: int = 7,
            min_age_days: float = 3.0,
            dry_run: bool = False) -> ArchiveResult:
    cands = candidates(lookback=lookback, min_age_days=min_age_days)
    arch = _archive_dir()
    moved: list[Path] = []
    if not dry_run and cands:
        arch.mkdir(parents=True, exist_ok=True)
    for c in cands:
        target = arch / c.case_path.name
        if dry_run:
            moved.append(target)
            continue
        try:
            shutil.move(str(c.case_path), str(target))
            moved.append(target)
        except OSError as e:
            log.warning("could not archive %s: %s", c.case_path, e)
    return ArchiveResult(
        n_candidates=len(cands),
        n_moved=len(moved),
        moved=moved,
        archive_dir=arch,
    )


def summary() -> str:
    cands = candidates()
    if not cands:
        return "(no archive candidates — all regression cases still active)"
    parts = [f"📦 {len(cands)} regression cases ready to archive"]
    for c in cands[:10]:
        line = f":{c.inferred_ref_line}" if c.inferred_ref_line else ""
        parts.append(f"  • {c.case_id}  ({c.inferred_ref_path}{line}, "
                      f"age {c.age_days:.1f}d)")
    if len(cands) > 10:
        parts.append(f"  (+{len(cands) - 10} more)")
    return "\n".join(parts)
