# install_icons.ps1 — install AIM and AIM AI Desktop shortcuts on Windows.
#
# Creates:
#     %USERPROFILE%\Desktop\AIM.lnk       — full menu (start.bat cli)
#     %USERPROFILE%\Desktop\AIM AI.lnk    — free-form AI assistant
#     Both Start-Menu shortcuts under  %APPDATA%\Microsoft\Windows\Start Menu\Programs\AIM\
#
# Re-run any time — overwrites.

param([switch]$NoStartMenu)

$ErrorActionPreference = "Stop"
$AimRoot = (Resolve-Path "$PSScriptRoot\..\..").Path
$IconSrc = Join-Path $AimRoot "scripts\desktop\icons"
$Desktop = [Environment]::GetFolderPath("Desktop")
$StartMenu = Join-Path ([Environment]::GetFolderPath("Programs")) "AIM"

function Bold($m) { Write-Host $m -ForegroundColor White }
function OK($m)   { Write-Host $m -ForegroundColor Green }

Bold "AIM desktop launcher installer (Windows)"
Write-Host "AIM_ROOT = $AimRoot"
Write-Host "Desktop  = $Desktop"
Write-Host ""

# ── 1. Build icons if missing ──────────────────────────────────────────────

if (-not (Test-Path "$IconSrc\aim.ico") -or -not (Test-Path "$IconSrc\aim_ai.ico")) {
    Bold "[1/3] building icon assets"
    $py = Join-Path $AimRoot "venv\Scripts\python.exe"
    if (-not (Test-Path $py)) { $py = "python" }
    & $py (Join-Path $AimRoot "scripts\desktop\build_icons.py")
}

# ── 2. Write a ReAct-loop launcher .bat for the AI shortcut ────────────────

Bold "[2/3] writing free-form AI loop launcher"

$AiEntry = Join-Path $AimRoot "scripts\desktop\ai_loop.bat"
$aiScript = @"
@echo off
cd /d "$AimRoot"
if exist venv\Scripts\activate.bat call venv\Scripts\activate.bat
python -c "import sys; sys.path.insert(0, r'$AimRoot');^
print('AIM AI assistant -- free-form ReAct loop. Empty line = quit.\n');^
from agents.generalist import run;^
^
while True:^
    try: task = input('you> ').strip()
    except (EOFError, KeyboardInterrupt): break
    if not task: break
    out = run(task, max_iters=12)
    print(); print(out['answer']); print()
    print(f\"[tools: {{', '.join(out['tools_used'])}}  iters: {{out['iters']}}]\n\")
"
pause
"@
# PowerShell here-strings can't keep ^ properly; write a clean Python file
# alongside and let the .bat just call it.

$aiPyFile = Join-Path $AimRoot "scripts\desktop\ai_loop.py"
@"
# Generated by install_icons.ps1 — free-form AIM AI loop entry.
import sys, os
sys.path.insert(0, r"$AimRoot")
print("AIM AI assistant -- free-form ReAct loop. Empty line = quit.\n")
from agents.generalist import run
while True:
    try:
        task = input("you> ").strip()
    except (EOFError, KeyboardInterrupt):
        break
    if not task:
        break
    out = run(task, max_iters=12)
    print()
    print(out["answer"])
    print()
    print(f"[tools: {', '.join(out['tools_used'])}  iters: {out['iters']}]\n")
"@ | Set-Content -Path $aiPyFile -Encoding UTF8

@"
@echo off
cd /d "$AimRoot"
if exist venv\Scripts\activate.bat call venv\Scripts\activate.bat
python "$aiPyFile"
pause
"@ | Set-Content -Path $AiEntry -Encoding ASCII

# ── 3. Create .lnk shortcuts ───────────────────────────────────────────────

Bold "[3/3] creating Desktop shortcuts"

function Make-Shortcut {
    param($Path, $Target, $Args, $Icon, $Description, $WorkDir)
    $shell = New-Object -ComObject WScript.Shell
    $sc = $shell.CreateShortcut($Path)
    $sc.TargetPath       = $Target
    $sc.Arguments        = $Args
    $sc.WorkingDirectory = $WorkDir
    $sc.IconLocation     = "$Icon, 0"
    $sc.Description      = $Description
    $sc.WindowStyle      = 1
    $sc.Save()
}

$startBat = Join-Path $AimRoot "start.bat"

# AIM full menu
Make-Shortcut -Path "$Desktop\AIM.lnk" `
              -Target "cmd.exe" `
              -Args "/k `"$startBat`" cli" `
              -Icon "$IconSrc\aim.ico" `
              -Description "Assistant of Integrative Medicine — full menu" `
              -WorkDir $AimRoot

# AIM AI free-form
Make-Shortcut -Path "$Desktop\AIM AI.lnk" `
              -Target "cmd.exe" `
              -Args "/k `"$AiEntry`"" `
              -Icon "$IconSrc\aim_ai.ico" `
              -Description "AIM AI assistant — free-form ReAct loop with tools" `
              -WorkDir $AimRoot

if (-not $NoStartMenu) {
    if (-not (Test-Path $StartMenu)) { New-Item -ItemType Directory -Path $StartMenu | Out-Null }
    Make-Shortcut -Path "$StartMenu\AIM.lnk" `
                  -Target "cmd.exe" -Args "/k `"$startBat`" cli" `
                  -Icon "$IconSrc\aim.ico" `
                  -Description "Assistant of Integrative Medicine" `
                  -WorkDir $AimRoot
    Make-Shortcut -Path "$StartMenu\AIM AI.lnk" `
                  -Target "cmd.exe" -Args "/k `"$AiEntry`"" `
                  -Icon "$IconSrc\aim_ai.ico" `
                  -Description "AIM AI assistant" `
                  -WorkDir $AimRoot
}

OK ""
OK "✓ done."
Write-Host ""
Write-Host "  Two shortcuts placed on the Desktop:"
Write-Host "    • AIM       — full menu"
Write-Host "    • AIM AI    — free-form AI assistant"
Write-Host ""
Write-Host "  Plus a Start-Menu folder 'AIM' (skip with -NoStartMenu)."
